analytics:
    sim_one_name: 'Normal Day'
    sim_two_name: 'No Transit Day'
    signalsrun: False 

    sim_one_path: "../../Results_Mobiliti/2023-05-10 - SF All except less than 0.1 miles/2023-05-10-sf_allminus01_baseline_060_links"
    sim_two_path: "../../Results_Mobiliti/2023-05-10 - SF Day without Transit/2023-05-10-sf_allminustransit_baseline_060_links"
    legs_one_path: "../../Results_Mobiliti/2023-05-10 - SF All except less than 0.1 miles/2023-05-10-sf_allminus01_baseline_060_legs/legs.tsv"
    legs_two_path: "../../Results_Mobiliti/2023-05-10 - SF Day without Transit/2023-05-10-sf_allminustransit_baseline_060_legs/legs.tsv"
    fpath : "avg_flow_rates.tsv"
    spath : "avg_speeds.tsv"
    fupath : "fuel_consumption.tsv"

    network_path : "../../Networks_Dataset/data/sf"
    city_links: "sf_links.csv"
    city_nodes: "sf_nodes.csv"

    processed_path : "processed_data"
     
report:
    report_upload_name: "No Transit Day Experiment"
    
